export const plantEmojis = {
  "Candy Blossom": "🍭",
  "Sugarbud": "🍬",
  "Honeylure": "🍯",
  "Roseberry": "🌹",
  "Heartbloom": "💖",
  "Amora Petal": "💞",
  "Moon Mango": "🌕",
  "Dream Lotus": "🪷",
  "Goldleaf Clover": "🍀",
  "Wishroot": "🌠",
  "Lucky Orchid": "🌸",
  "Ember Vine": "🔥",
  "Spookleaf": "👻",
  "Chillberry": "🔵",
  "Frostleaf Fern": "❄️",
  "Starlight Ivy": "✨",
  "Carrot": "🥕",
  "Strawberry": "🍓",
  "Blueberry": "🫐",
  "Orange Tulip": "🌷",
  "Tomato": "🍅",
  "Daffodil": "🌼",
  "Corn": "🌽",
  "Pumpkin": "🎃",
  "Watermelon": "🍉",
  "Bamboo": "🎋",
  "Apple": "🍎",
  "Coconut": "🥥",
  "Cactus": "🌵",
  "Dragon Fruit": "🐉",
  "Mango": "🥭",
  "Mushroom": "🍄",
  "Grape": "🍇",
  "Pepper": "🌶️",
  "Cacao": "🍫",
  "Beanstalk": "🌱",
  "Ember Lily": "🌺",
  "Sugar Apple": "🍏",
  "Cocode": "🟤",
  "Ownerler": "💪",
  "Admingo": "🟠",
  "Gordan": "😎"
};

export const plantRarities = {
  "Candy Blossom": "event",
  "Sugarbud": "event",
  "Honeylure": "event",
  "Roseberry": "event",
  "Heartbloom": "event",
  "Amora Petal": "event",
  "Moon Mango": "event",
  "Dream Lotus": "event",
  "Goldleaf Clover": "event",
  "Wishroot": "event",
  "Lucky Orchid": "event",
  "Ember Vine": "event",
  "Spookleaf": "event",
  "Chillberry": "event",
  "Frostleaf Fern": "event",
  "Starlight Ivy": "event",
  "Carrot": "common",
  "Strawberry": "common",
  "Blueberry": "common",
  "Orange Tulip": "common",
  "Tomato": "common",
  "Daffodil": "common",
  "Corn": "common",
  "Pumpkin": "common",
  "Watermelon": "common",
  "Bamboo": "common",
  "Apple": "common",
  "Coconut": "common",
  "Cactus": "common",
  "Dragon Fruit": "rare",
  "Mango": "common",
  "Mushroom": "common",
  "Grape": "common",
  "Pepper": "common",
  "Cacao": "common",
  "Beanstalk": "rare",
  "Ember Lily": "rare",
  "Sugar Apple": "common",
  "Cocode": "admin",
  "Ownerler": "admin",
  "Admingo": "admin",
  "Gordan": "mythical"
};